// F3.3 Unit Evidence + Historical Scope Hardening Tests

export const F3_3_TestManifest = [
    "F3.3.1 selected Unit evidence index scoped correctly.",
    "F3.3.2 descendant inclusion matches scopeMode.",
    "F3.3.3 descendant exclusion matches scopeMode if unit_only.",
    "F3.3.4 sibling evidence absent.",
    "F3.3.5 unrelated evidence absent.",
    "F3.3.6 Daily Report authorized evidence accepted.",
    "F3.3.7 out-of-scope report evidence rejected.",
    "F3.3.8 authorized Task evidence accepted.",
    "F3.3.9 Task-specific unauthorized evidence rejected.",
    "F3.3.10 authorized KPI assignment evidence accepted.",
    "F3.3.11 authorized KPI item evidence accepted.",
    "F3.3.12 sibling KPI evidence rejected.",
    "F3.3.13 random evidence rejected.",
    "F3.3.14 wrong scoreMode rejected.",
    "F3.3.15 historical KPI snapshot preserved after Staff move.",
    "F3.3.16 current Staff unit does not rewrite historical KPI.",
    "F3.3.17 organization KPI stays organization-level.",
    "F3.3.18 cross-module insight needs >=2 modules.",
    "F3.3.19 each cross-module evidence independently authorized.",
    "F3.3.20 invalid second evidence invalidates/normalizes insight.",
    "F3.3.21 permission change blocks later drill-down.",
    "F3.3.22 old AI result cannot grant access.",
    "F3.3.23 PII minimized.",
    "F3.3.24 email absent unless explicitly required.",
    "F3.3.25 phone absent.",
    "F3.3.26 prompt injection cannot widen scope.",
    "F3.3.27 injection cannot access sibling unit.",
    "F3.3.28 injection cannot rank Staff.",
    "F3.3.29 injection cannot reveal API key.",
    "F3.3.30 injection cannot mutate organization/KPI.",
    "F3.3.31 no cross-unit performance comparison.",
    "F3.3.32 audit excludes raw business narrative.",
    "F3.3.33 audit excludes secrets.",
    "F3.3.34 business state unchanged.",
    "F3.3.35 Executive Overview F2 regression PASS.",
    "F3.3.36 AI Context regression PASS.",
    "F3.3.37 Task Context regression PASS.",
    "F3.3.38 KPI Context regression PASS.",
    "F3.3.39 backend build PASS.",
    "F3.3.40 fixtures cleaned."
];
